### PR TITLE
Add email text field

### PR DESCRIPTION
**Pull request by cfalucho**
- Added email text field
- Created user-defined components for SignUp.

### CODE REVIEW

**Comment by exelarios** [comment]
Where is `react-hook-form` being used?

**Comment by cfalucho** [comment]
Forgot to remove the dependency. It is not being used at all.

**Comment by exelarios** [comment]
Ah, alrighty. Thanks for the fast response. 👍

**Comment by cfalucho** [comment]
Of course, let me know if there are any other changes that needs to be done.

**Comment by exelarios** [comment]
No, it looks good. Going to merge it right now.

**Pull request merged**
