### PR TITLE
Added dates between Feed page cards

### PR DESCRIPTION
**Pull request by lchua2314**
**Feed Page**
- Sorted by date (most upcoming events)
- Same dates will stack the cards and not show the same date again
- Formatting Example: Sat, Nov 16, 2019
- Popup card has UTC date formatting, **but the time zone is wrong so it will show a day before.**
- Indents updated for 4 spaces

**Events Page**
- **WARNING** from emulator after RVSP button press: **Each child in a list should have a unique "key" prop**
- Sorted by date (most upcoming events)
- Non-expanded card: Has UTC date formatting
- Popup card: Has UTC date formatting
- NOTE: Cannot add newly created Event cards to Feed page some error like: undefined can't be used in JSON.stringify(data).split( Update: FIXED

**Dummy Data in data/events.js**
- Updated "date"s with backend formatting (ISO)
- NOTE: "date" will need to be renamed to "startDate" later. Update: FIXED

Please merge if no issues after checking.

### CODE REVIEW

**Comment by exelarios** [comment]
Awesome job with sorting the feed by the dates, but you want me to see if I can fix the parsing error before merging into master?

**Comment by lchua2314** [comment]
Actually, let me fix it

**Comment by lchua2314** [comment]
I switched all the dummy data's "date" to "startDate". The dummy data provided by Peter is still showing the wrong timezone, but the newly created events' dates are showing PST. I think it will be fixed later from the backend. So everything should be fixed except for the warning. If that's fine with you and there are no more errors, please merge. Thanks.

Update: The below commit makes sure the user cannot see Event cards that the user RSVPed to. The Event card will come back if the user unsubs to the respective Feed page card.

Update 2: Fixed a bug in which cards aren't being sorted by upcoming date.

**Comment by exelarios** [comment]
Alrighty looks good now. Awesome job!
Just wanted to make sure, we're pushing errorless code onto master.

**Review by exelarios — APPROVED** [review]

**Pull request merged**
