### PR TITLE
Added edit event button

### PR DESCRIPTION
**Pull request by cfalucho**
- Created an EditEvent component, just used code from CreateEvent and only changed "Submit" button to "Save Changes"
- Added the Edit Event button
- Added an additional stack screen for Edit Event

### CODE REVIEW

**Comment by exelarios** [comment]
This doesn't edit the existing event but creates a new one.

**Comment by cfalucho** [comment]
can i just navigate it back to create events then?

**Comment by cfalucho** [comment]
Refactored to remove the edit component and to point it back to the Create Event form. Only problem i'm running into is saving the data to display current data.

**Comment by exelarios** [comment]
Merged with #52

**Pull request closed without merging**
